---
- hosts: cluster
  connection: local
  gather_facts: false
  vars:
    features_by_cluster_type:
      classic:
        all_available_features:
          - manage-with-acm
          - redhat-internal-certificate
          - coe-sso
          - external-secrets
          - lvms
          - rhoai
          - look-and-feel
          - workload-partitioning
        default_features:
          - manage-with-acm
          - redhat-internal-certificate
          - coe-sso
          - look-and-feel
      hosted:
        all_available_features:
          - redhat-internal-certificate
          - coe-sso
          # - lvms - not tested
          # - rhoai - not tested
          - look-and-feel
        default_features:
          - redhat-internal-certificate
          - coe-sso
          - look-and-feel
  tasks:
    # - debug: msg="{{ inventory_hostname }}"
    - name: Create coe-lab-stormshift-notifications notification template
      awx.awx.notification_template:
        state: present
        name: "coe-lab-stormshift-notifications"
        organization: "stormshift"
        notification_type: email
        notification_configuration:
          sender: "coe-lab-stormshift-notifications@redhat.com"
          recipients:
            - "coe-lab-stormshift-notifications@redhat.com"
          host: "smtp.corp.redhat.com"
          port: 25
          username: ''
          password: ''
          use_tls: no
          use_ssl: no

    - name: "Create jobs: StormShift Cluster Mgmt - {{ inventory_hostname }}"
      awx.awx.job_template:
        name: "🌪️ StormShift Cluster Mgmt - {{ inventory_hostname }}"
        description: "Do NOT edit, managed by Ansible: https://github.com/stormshift/automation/blob/master/configure-job-templates.yaml"
        job_type: "run"
        organization: "stormshift"
        inventory: "stormshift-inventory"
        project: "stormshift-automation"

        playbook: "stormshift-cluster-mgmt.yaml"
        execution_environment: "stormshift-automation-execution-environment-202410072305"

        credentials:
          - "automation-vault"
          - "coe-muc"
          - "ipa-admin"
          - "redhat-vault"
          - "rhca-account"
          - "stormshift-automation-pullsecret"
          - "stormshift-automation-ssh"
          - "14" # SNO AAP
        state: "present"
        survey_enabled: yes
        allow_simultaneous: false
        notification_templates_error:
          - coe-lab-stormshift-notifications
        notification_templates_started:
          - coe-lab-stormshift-notifications
        notification_templates_success:
          - coe-lab-stormshift-notifications
        extra_vars:
          stormshift_cluster_name: "{{ inventory_hostname }}"
        ask_variables_on_launch: true
        survey_spec: |
          {
            "description": "",
            "name": "",
            "spec": [
                {
                    "choices": [
                        "deploy",
                        "destroy",
                        "add-features",
                        "remove-features"
                    ],
                    "default": "",
                    "max": 1024,
                    "min": 0,
                    "new_question": false,
                    "question_description": "What should we do?",
                    "question_name": "Action",
                    "required": true,
                    "type": "multiplechoice",
                    "variable": "stormshift_cluster_action"
                },
                {
                    "choices": [
                      {% for feature in features_by_cluster_type[cluster_type].all_available_features %}
                        "{{ feature }}"{% if not loop.last %},{% endif %}
                      {% endfor %}
                    ],
                    {% if stormshift_cluster_features is defined %}
                    "default": "{{ stormshift_cluster_features | join('\n') }}",
                    {% else %}
                    "default": "{{ features_by_cluster_type[cluster_type].default_features | join('\n') }}",
                    {% endif %}
                    "max": 1024,
                    "min": 0,
                    "new_question": false,
                    "question_description": "Select a couple of cluster features",
                    "question_name": "Cluster features",
                    "required": false,
                    "type": "multiselect",
                    "variable": "stormshift_cluster_features"
                }
            ]
          }
