---
version: 3

images:
  base_image:
    name: quay.io/fedora/fedora:latest

additional_build_steps:
  append_final:
    - ADD execution-environment/Current-IT-Root-CAs.crt /etc/pki/ca-trust/source/anchors/Current-IT-Root-CAs.crt
    - RUN update-ca-trust

dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  system:
    - openssh-clients
    - sshpass
    - git
  python:
    # Import for community.general.json_query
    - jmespath
  galaxy:
    collections:
      - name: community.general
      - name: community.kubernetes
      - name: kubernetes.core
      - name: ansible.posix
      - name: community.crypto
      - name: kubevirt.core

      - name: community.libvirt
        src: git+https://github.com/ansible-collections/community.libvirt

      - name: community.vmware
      - name: awx.awx
