---
version: 3

options:
  package_manager_path: /usr/bin/microdnf

images:
  base_image:
    name: 'registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel9:1.0'

additional_build_steps:
  prepend_builder:
    - ENV PKGMGR_OPTS="--nodocs --setopt=install_weak_deps=0 --setopt=rhocp-4.17-for-rhel-9-x86_64-rpms.enabled=true"
  prepend_final:
    - ENV PKGMGR_OPTS="--nodocs --setopt=install_weak_deps=0 --setopt=rhocp-4.17-for-rhel-9-x86_64-rpms.enabled=true"
  append_final:
    - ADD execution-environment/Current-IT-Root-CAs.crt /etc/pki/ca-trust/source/anchors/Current-IT-Root-CAs.crt
    - RUN update-ca-trust

dependencies:
  system:
    - nmstate
  galaxy:
    collections:
# ToDo: add version numbers!
      - name: community.general
      - name: community.kubernetes
      - name: redhat.openshift
      - name: kubernetes.core
      - name: ansible.posix
      - name: community.crypto
      - name: kubevirt.core

      - name: community.libvirt
        src: git+https://github.com/ansible-collections/community.libvirt
      - name: community.vmware
      - name: awx.awx
      - name: community.hashi_vault
