---
- name: Fetch kubeconfig from vault
  ansible.builtin.include_role:
    name: internal-fetch-kubeconfig

- name: Install External Secrets operator
  kubernetes.core.k8s:
    kubeconfig: "{{ cluster_access_kubeconfig }}"
    state: present
    definition:
      - kind: Namespace
        apiVersion: v1
        metadata:
          name: external-secrets

      - kind: Secret
        apiVersion: v1
        metadata:
          name: redhat-vault
          namespace: external-secrets
        data:
          token: "{{ lookup('ansible.builtin.env', 'RH_VAULT_SECRET_ID' )| b64encode  }}"
        type: Opaque

      - kind: Subscription
        apiVersion: operators.coreos.com/v1alpha1
        metadata:
          name: external-secrets-operator
          namespace: openshift-operators
        spec:
          channel: alpha
          installPlanApproval: Automatic
          name: external-secrets-operator
          source: community-operators
          sourceNamespace: openshift-marketplace

- name: Wait for operator pod to be ready
  kubernetes.core.k8s_info:
    kubeconfig: "{{ cluster_access_kubeconfig }}"
    kind: Deployment
    name: external-secrets-operator-controller-manager
    namespace: openshift-operators
    wait: yes
    wait_timeout: 300
    wait_condition:
      type: Available
      status: True
      reason: MinimumReplicasAvailable

- name: Configure External Secrets operator
  kubernetes.core.k8s:
    kubeconfig: "{{ cluster_access_kubeconfig }}"
    state: present
    src: OperatorConfig.yaml

- name: Wait for controler pods to be ready
  kubernetes.core.k8s_info:
    kubeconfig: "{{ cluster_access_kubeconfig }}"
    kind: Deployment
# no name here, its three deployments, we wait for all of them to become Available
    namespace: external-secrets
    wait: yes
    wait_timeout: 300
    wait_condition:
      type: Available
      status: True
      reason: MinimumReplicasAvailable

- name: Create ClusterSecretStore
  kubernetes.core.k8s:
    kubeconfig: "{{ cluster_access_kubeconfig }}"
    state: present
    wait: yes
    wait_timeout: 300
    wait_condition:
      type: Ready
      status: True
      reason: Valid
    definition:
      kind: ClusterSecretStore
      apiVersion: external-secrets.io/v1beta1
      metadata:
        name: redhat-vault
      spec:
        provider:
          vault:
            auth:
              appRole:
                path: approle
                roleId: "{{ lookup('ansible.builtin.env', 'RH_VAULT_ROLE_ID' ) }}"
                secretRef:
                  key: token
                  name: redhat-vault
                  namespace: external-secrets
            caProvider:
              key: ca-bundle.crt
              name: redhat-current-it-root-cas
              namespace: openshift-config
              type: ConfigMap
            path: apps
            server: "{{ lookup('ansible.builtin.env', 'RH_VAULT_URL' ) }}"
            version: v2
