---
- name: Fetch kubeconfig from vault
  ansible.builtin.include_role:
    name: internal-fetch-kubeconfig

- name: Remove External Secrets CRs
  ignore_errors: true # fails when CRD does not exist otherwise
  kubernetes.core.k8s:
    kubeconfig: "{{ cluster_access_kubeconfig }}"
    state: absent
    wait: yes
    wait_timeout: 300
    definition:
      - kind: ClusterSecretStore
        apiVersion: external-secrets.io/v1beta1
        metadata:
          name: redhat-vault

      - kind: OperatorConfig
        apiVersion: operator.external-secrets.io/v1alpha1
        metadata:
          name: coe
          namespace: external-secrets

- name: Remove ClusterServiceVersion
  kubernetes.core.k8s:
    kubeconfig: "{{ cluster_access_kubeconfig }}"
    state: absent
    delete_all: true
    wait: yes
    wait_timeout: 300
    kind: ClusterServiceVersion
    api_version: operators.coreos.com/v1alpha1
    namespace: openshift-operators
    label_selectors:
      - operators.coreos.com/external-secrets-operator.openshift-operators

- name: Remove Subscription and Namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ cluster_access_kubeconfig }}"
    state: absent
    wait: yes
    wait_timeout: 300
    definition:
      - kind: Subscription
        apiVersion: operators.coreos.com/v1alpha1
        metadata:
          name: external-secrets-operator
          namespace: openshift-operators
      - kind: Namespace
        apiVersion: v1
        metadata:
          name: external-secrets

- name: Remove CRDs
  kubernetes.core.k8s:
    kubeconfig: "{{ cluster_access_kubeconfig }}"
    state: absent
    delete_all: true
    wait: yes
    wait_timeout: 300
    kind: CustomResourceDefinition
    api_version: apiextensions.k8s.io/v1
    label_selectors:
      - operators.coreos.com/external-secrets-operator.openshift-operators
